const mongoose = require('mongoose');

const notificationSchema = new mongoose.Schema({
  recipient: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  message: {
    type: String,
    required: true
  },
  type: {
    type: String,
    enum: ['order_update', 'chat', 'system', 'payment'],
    default: 'system'
  },
  orderId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Order'
  },
  isRead: {
    type: Boolean,
    default: false
  }
}, { timestamps: true });

// 1. Compound Index: Faster unread count queries (recipient + isRead)
notificationSchema.index({ recipient: 1, isRead: 1 });

// 2. TTL Index: Auto-delete notifications after 7 days
// Note: Index is applied to 'createdAt' field generated by timestamps
notificationSchema.index({ createdAt: 1 }, { expireAfterSeconds: 60 * 60 * 24 * 7 });

const Notification = mongoose.model('Notification', notificationSchema);
module.exports = Notification;
